bind = Super, w, exec, firefox
bind = SUPER CTRL, l, resizeactive, 150 0
bind = SUPER CTRL, h, resizeactive, -150 0
bind = SUPER CTRL, k, resizeactive, 0 -150
bind = SUPER CTRL, j, resizeactive, 0 150
bind = SUPER, l, movefocus, r
bind = SUPER, h, movefocus, l
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

