monitor = Virtual-1, 1920x1080@60, auto, 1
exec-once = wal -R
source = /home/sarem/.cache/wal/colors-hyprland.conf

general {
	gaps_in = 3
	gaps_out = 20

	col.active_border = $color1 $color3 45deg
}

decoration {
	rounding = 6
	active_opacity = 1.0
	inactive_opacity = 0.75
	blur {
		enabled = true
		size = 5
		passes = 2
		new_optimizations = true
		ignore_opacity = true
	}
}

windowrule = opacity 0.85 1.0, match:class ^(foot)$

animations {
	enabled = false
}

misc {
	disable_hyprland_logo = true
	disable_splash_rendering = true
	vfr = true
}

dwindle {
	force_split = 2
	preserve_split = true
}

